// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avvytaitpddyagqvawxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dnl0YWl0cGRkeWFncXZhd3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDU2MzYsImV4cCI6MjA2MzY4MTYzNn0.J1XOjKy2WRauK3KFlbirlThZo7JBcsRk6EProPfDiNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);